-- write your table creation sql here!
drop table if exists accident ;
create table accident (
    crash_date timestamp,
    crash_time time,
    borough varchar(255),
    zip_code char(10),
    latitude varchar(255),
    longitude varchar(255),
    loc varchar(255),
    on_street_name varchar(255),
    cross_street_name varchar(255),
    off_street_name varchar(255),
    number_of_persons_injured int,
    number_of_persons_killed int,
    number_of_pedestrians_injured int,
    number_of_pedestrians_killed int,
    number_of_cyclist_injured int,
    number_of_cyclist_killed int,
    number_of_motorist_injured int,
    number_of_motorist_killed int,
    contributing_factor_vehicle_1 varchar(255),
    contributing_factor_vehicle_2 varchar(255),
    contributing_factor_vehicle_3 varchar(255),
    contributing_factor_vehicle_4 varchar(255),
    contributing_factor_vehicle_5 varchar(255),
    collision_id int not null unique primary key,
    vehicle_type_code_1 varchar(255),
    vehicle_type_code_2 varchar(255),
    vehicle_type_code_3 varchar(255),
    vehicle_type_code_4 varchar(255),
    vehicle_type_code_5 varchar(255));
